In [2]:
import pandas as pd
import numpy as np

In [18]:
subway_ = pd.read_csv('./전체_도시철도역사정보_20230317.csv', encoding='cp949')
subway_tmp = pd.read_csv('./서울교통공사_1_8호선 역사 좌표(위경도) 정보_20211231.csv', encoding='cp949')

In [5]:
subway_.isnull().sum()

역번호          0
역사명          0
노선번호         0
노선명          0
영문역사명        0
한자역사명        0
환승역구분        0
환승노선번호     744
환승노선명      744
역위도        449
역경도        449
운영기관명        0
역사도로명주소      0
역사전화번호       0
데이터기준일자      0
dtype: int64

In [7]:
seoul_subway = subway_[subway_['역사도로명주소'].str.contains('서울')]
gg_subway = subway_[subway_['역사도로명주소'].str.contains('경기')]

In [21]:
seoul_subway.keys()

Index(['역번호', '역사명', '노선번호', '노선명', '영문역사명', '한자역사명', '환승역구분', '환승노선번호',
       '환승노선명', '역위도', '역경도', '운영기관명', '역사도로명주소', '역사전화번호', '데이터기준일자'],
      dtype='object')

In [23]:
seoul_subway = seoul_subway[['역사명','역위도','역경도','역사도로명주소']]
gg_subway = gg_subway[['역사명','역위도','역경도','역사도로명주소']]

In [25]:
seoul_subway[seoul_subway['역위도'].isnull()]

          역사명  역위도  역경도               역사도로명주소
345     북한산우이  NaN  NaN  서울특별시 강북구 삼양로 지하 676
346      솔밭공원  NaN  NaN     서울특별시 강북구 삼양로 595
347  4.19민주묘지  NaN  NaN     서울특별시 강북구 삼양로 519
348       가오리  NaN  NaN     서울특별시 강북구 삼양로 426
349        화계  NaN  NaN     서울특별시 강북구 삼양로 341
..        ...  ...  ...                   ...
699       구반포  NaN  NaN   서울특별시 서초구 신반포로 지하17
700       신반포  NaN  NaN  서울특별시 서초구 신반포로 지하105
701     고속터미널  NaN  NaN  서울특별시 서초구 신반포로 지하188
702        사평  NaN  NaN  서울특별시 서초구 사평대로 지하285
703       신논현  NaN  NaN  서울특별시 강남구 봉은사로 지하102

[299 rows x 4 columns]

In [26]:
gg_subway[gg_subway['역위도'].isnull()]

                  역사명  역위도  역경도                       역사도로명주소
170               까치울  NaN  NaN  경기도 부천시 원미구 길주로 지하 626 (춘의동)
171           부천종합운동장  NaN  NaN  경기도 부천시 원미구 길주로 지하 502 (춘의동)
172                춘의  NaN  NaN  경기도 부천시 원미구 길주로 지하 406 (춘의동)
173               신중동  NaN  NaN   경기도 부천시 원미구 길주로 지하 314 (중동)
174              부천시청  NaN  NaN   경기도 부천시 원미구 길주로 지하 202 (중동)
175                상동  NaN  NaN   경기도 부천시 원미구 길주로 지하 104 (상동)
391               양촌역  NaN  NaN           경기 김포시 양촌읍 양촌역길 107
392               구래역  NaN  NaN              경기 김포시 김포한강7로 87
393               마산역  NaN  NaN          경기 김포시 김포한강3로 지하 442
394               장기역  NaN  NaN           경기 김포시 김포한강1로 지하 59
395               운양역  NaN  NaN          경기 김포시 김포한강1로 지하 235
396             걸포북변역  NaN  NaN           경기 김포시 김포대로 지하 1040
397         사우(김포시청)역  NaN  NaN            경기 김포시 김포대로 지하 852
398               풍무역  NaN  NaN            경기 김포시 김포대로 지하 710
399               고촌역  NaN  NaN        경기 김포시 고촌읍 김포대로 지하 350
401            별내별가람역  NaN  NaN          경기도 남양주시 별내3로 지하 345
402               오남역  NaN  NaN     경기도 남양주시 오남읍 진건오남로 지하 929
403               진접역  NaN  NaN      경기도 남양주시 진접읍 경복대로 지하 244
464                지축  NaN  NaN      경기도 고양시 덕양구 삼송로 300(지축동)
575                미사  NaN  NaN      경기도 하남시 미사강변동로 지하90(망월동)
576              하남풍산  NaN  NaN        경기도 하남시 덕풍서로 지하50(덕풍동)
577       하남시청(덕풍?신장)  NaN  NaN       경기도 하남시 하남대로 지하820(덕풍동)
578             하남검단산  NaN  NaN        경기도 하남시 대청로 지하100(창우동)
619                장암  NaN  NaN         경기도 의정부시 동일로 121(장암동)
657                철산  NaN  NaN         경기도 광명시 철산로 지하13(철산동)
658             광명사거리  NaN  NaN        경기도 광명시 오리로 지하980(광명동)
672               남위례  NaN  NaN      경기도 성남시 수정구 공원로 601(복정동)
673                산성  NaN  NaN    경기도 성남시 수정구 수정로 지하365(신흥동)
674  남한산성입구(성남법원·검찰청)  NaN  NaN   경기도 성남시 수정구 산성대로 지하445(단대동)
675             단대오거리  NaN  NaN   경기도 성남시 수정구 산성대로 지하365(신흥동)
676                신흥  NaN  NaN   경기도 성남시 수정구 산성대로 지하280(신흥동)
677                수진  NaN  NaN   경기도 성남시 수정구 산성대로 지하200(수진동)
678                모란  NaN  NaN   경기도 성남시 수정구 산성대로 지하100(수진동)
704                발곡  NaN  NaN              경기도 의정부시 장곡로 258
705                회룡  NaN  NaN              경기도 의정부시 평화로 363
706                범골  NaN  NaN              경기도 의정부시 신흥로 141
707            경전철의정부  NaN  NaN              경기도 의정부시 신흥로 237
708             의정부시청  NaN  NaN               경기도 의정부시 의정로 69
709                흥선  NaN  NaN             경기도 의정부시 호국로 1197
710             의정부중앙  NaN  NaN             경기도 의정부시 호국로 1305
711                동오  NaN  NaN              경기도 의정부시 장곡로 471
712                새말  NaN  NaN              경기도 의정부시 장곡로 551
713          경기도청북부청사  NaN  NaN              경기도 의정부시 장곡로 615
714                효자  NaN  NaN           경기도 의정부시 부용로 159-40
715                곤제  NaN  NaN              경기도 의정부시 천보로 173
716                어룡  NaN  NaN              경기도 의정부시 충의로 125
717                송산  NaN  NaN               경기도 의정부시 충의로 59
718                탑석  NaN  NaN               경기도 의정부시 충의로 20